export default async function Home() {
  return (
    <div>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
      <h1>Landing</h1>
    </div>
  );
}
